notify:
  - name: Send_SMS
    platform: rest
    resource: http://IP.OF.YOUR.SMSEAGLE/api/v2/messages/sms_single
    method: POST_JSON
    data:
      "to": "{{ data.number }}"
      "text": "{{ message }}"
      "access_token": "YOUR-API-ACCESS-TOKEN"
    message_param_name: "text"

  - name: Make_a_Call
    platform: rest
    resource: http://IP.OF.YOUR.SMSEAGLE/api/v2/calls/ring
    method: POST_JSON
    data:
      "to": ["{{ data.number }}"]
      "duration": 20
      "access_token": "YOUR-API-ACCESS-TOKEN"

  - name: Make_TTS_Call
    platform: rest
    resource: http://IP.OF.YOUR.SMSEAGLE/api/v2/calls/tts_advanced
    method: POST_JSON
    data:
      "to": ["{{ data.number }}"]
      "voice_id": 3
      "text": "{{ message }}"
      "access_token": "YOUR-API-ACCESS-TOKEN"
    message_param_name: "text"
